IF( NOT NOVA_MODULES_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_MODULES_ROOT /opt/nova/packages )
  ELSE()
    SET( NOVA_MODULES_ROOT ${NOVA_ROOT}/modules )
  ENDIF()

  MESSAGE( STATUS "No NOVA_MODULES_ROOT specified, using default: ${NOVA_MODULES_ROOT}" )
ENDIF()


IF( CORE_MODULES_FIND_COMPONENTS )
  SET( MODULE_FILE ${NOVA_MODULES_ROOT}/${CORE_MODULES_FIND_COMPONENTS}/MODULE.cmake )
  IF( EXISTS ${MODULE_FILE} )
    INCLUDE( ${MODULE_FILE} )
  ELSE()
    MESSAGE( FATAL_ERROR "Module not found: ${CORE_MODULES_FIND_COMPONENTS} [${MODULE_FILE}]" )
  ENDIF()
ENDIF()
