LIST( APPEND CMAKE_MODULE_PATH "${NOVA_ROOT}/nova-cmake" )

MESSAGE( STATUS "CMAKE_MODULE_PATH: ${CMAKE_MODULE_PATH}" )

IF( NOT DEFINED CMAKE_PREFIX_PATH )
  IF( NOT "$ENV{CMAKE_PREFIX_PATH}" STREQUAL "" )
    STRING( REPLACE ":" ";" CMAKE_PREFIX_PATH $ENV{CMAKE_PREFIX_PATH} )
  ENDIF()
ENDIF()

MESSAGE( STATUS "CMAKE_PREFIX_PATH: ${CMAKE_PREFIX_PATH}" )
