IF( NOT NOVA_RTCAN_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_RTCAN_ROOT /opt/nova/rtcan )
  ELSE()
    SET( NOVA_RTCAN_ROOT ${NOVA_ROOT}/core-comm-can )
  ENDIF()

  MESSAGE( STATUS "No NOVA_RTCAN_ROOT specified, using default: ${NOVA_RTCAN_ROOT}" )
ENDIF()

SET( NOVA_RTCAN_SOURCES
  ${NOVA_RTCAN_ROOT}/src/rtcan.c
  ${NOVA_RTCAN_ROOT}/src/msgqueue.c
  ${NOVA_RTCAN_ROOT}/src/hrt.c
  ${NOVA_RTCAN_ROOT}/src/srt.c
  ${NOVA_RTCAN_ROOT}/platforms/STM32/rtcan_lld_can.c
  ${NOVA_RTCAN_ROOT}/platforms/STM32/rtcan_lld_tim.c
)

SET( NOVA_RTCAN_INCLUDE_DIRS
  ${NOVA_RTCAN_ROOT}/include
  ${NOVA_RTCAN_ROOT}/platforms/STM32/
)

LIST( REMOVE_DUPLICATES NOVA_RTCAN_SOURCES )
LIST( REMOVE_DUPLICATES NOVA_RTCAN_INCLUDE_DIRS )

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( Nova_RTCAN DEFAULT_MSG NOVA_RTCAN_SOURCES NOVA_RTCAN_INCLUDE_DIRS )
