IF( NOT NOVA_CORE_HW_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_CORE_HW_ROOT /opt/nova/middleware )
  ELSE()
    SET( NOVA_CORE_HW_ROOT ${NOVA_ROOT}/core-hw )
  ENDIF()

  MESSAGE( STATUS "No NOVA_CORE_HW_ROOT specified, using default: ${NOVA_CORE_HW_ROOT}" )
ENDIF()

SET( NOVA_CORE_HW_SOURCES
  ${NOVA_CORE_HW_ROOT}/src/core-hw.cpp
  ${NOVA_CORE_HW_ROOT}/src/SDU.cpp
)

SET( NOVA_CORE_HW_INCLUDE_DIRS
  ${NOVA_CORE_HW_ROOT}/include
  ${NOVA_CORE_HW_ROOT}/port/chibios/include
)

IF( NOVA_CORE_HW_SOURCES )
  LIST( REMOVE_DUPLICATES NOVA_CORE_HW_SOURCES )
ENDIF()

IF( NOVA_CORE_HW_INCLUDE_DIRS )
  LIST( REMOVE_DUPLICATES NOVA_CORE_HW_INCLUDE_DIRS )
ENDIF()

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( NovaCore_HW DEFAULT_MSG NOVA_CORE_HW_SOURCES NOVA_CORE_HW_INCLUDE_DIRS )
