IF( NOT NOVA_CORE_UTILS_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_CORE_UTILS_ROOT /opt/nova/middleware )
  ELSE()
    SET( NOVA_CORE_UTILS_ROOT ${NOVA_ROOT}/core-utils )
  ENDIF()

  MESSAGE( STATUS "No NOVA_CORE_UTILS_ROOT specified, using default: ${NOVA_CORE_UTILS_ROOT}" )
ENDIF()

SET( NOVA_CORE_UTILS_SOURCES
  ${NOVA_CORE_UTILS_ROOT}/src/core-utils.cpp
)

SET( NOVA_CORE_UTILS_INCLUDE_DIRS
  ${NOVA_CORE_UTILS_ROOT}/include
)

IF( NOVA_CORE_UTILS_SOURCES )
  LIST( REMOVE_DUPLICATES NOVA_CORE_UTILS_SOURCES )
ENDIF()

IF( NOVA_CORE_UTILS_INCLUDE_DIRS )
LIST( REMOVE_DUPLICATES NOVA_CORE_UTILS_INCLUDE_DIRS )
ENDIF()

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( NovaCore_Utils DEFAULT_MSG NOVA_CORE_UTILS_SOURCES NOVA_CORE_UTILS_INCLUDE_DIRS )
