IF( NOT NOVA_CORE_TRANSPORT_RTCAN_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_CORE_TRANSPORT_RTCAN_ROOT /opt/nova/middleware )
  ELSE()
    SET( NOVA_CORE_TRANSPORT_RTCAN_ROOT ${NOVA_ROOT}/core-transport-rtcan )
  ENDIF()

  MESSAGE( STATUS "No NOVA_CORE_TRANSPORT_RTCAN_ROOT specified, using default: ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}" )
ENDIF()

SET( NOVA_CORE_TRANSPORT_RTCAN_SOURCES
  ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}/src/core-transport-rtcan.cpp
)

SET( NOVA_CORE_TRANSPORT_RTCAN_INCLUDE_DIRS
  ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}/include
)

IF( CORE_USE_RTCANTRANSPORT )
  SET( TRANSPORT_SOURCES
    ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}/src/RTCANTransport.cpp
    ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}/src/RTCANPublisher.cpp
    ${NOVA_CORE_TRANSPORT_RTCAN_ROOT}/src/RTCANSubscriber.cpp
  )
  
  LIST( APPEND NOVA_CORE_TRANSPORT_RTCAN_SOURCES ${TRANSPORT_SOURCES} )
ENDIF()

IF( NOVA_CORE_TRANSPORT_RTCAN_SOURCES )
  LIST( REMOVE_DUPLICATES NOVA_CORE_TRANSPORT_RTCAN_SOURCES )
ENDIF()

IF( NOVA_CORE_TRANSPORT_RTCAN_INCLUDE_DIRS )
  LIST( REMOVE_DUPLICATES NOVA_CORE_TRANSPORT_RTCAN_INCLUDE_DIRS )
ENDIF()

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( NovaCore_Transport_RTCAN DEFAULT_MSG NOVA_CORE_TRANSPORT_RTCAN_SOURCES NOVA_CORE_TRANSPORT_RTCAN_INCLUDE_DIRS )
