IF( NOT NOVA_CORE_TRANSPORT_DEBUG_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_CORE_TRANSPORT_DEBUG_ROOT /opt/nova/middleware )
  ELSE()
    SET( NOVA_CORE_TRANSPORT_DEBUG_ROOT ${NOVA_ROOT}/core-transport-debug )
  ENDIF()

  MESSAGE( STATUS "No NOVA_CORE_TRANSPORT_DEBUG_ROOT specified, using default: ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}" )
ENDIF()

SET( NOVA_CORE_TRANSPORT_DEBUG_SOURCES
  ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}/src/core-transport-debug.cpp
)

SET( NOVA_CORE_TRANSPORT_DEBUG_INCLUDE_DIRS
  ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}/include
)

IF( CORE_USE_DEBUGTRANSPORT )
  SET( TRANSPORT_SOURCES
    ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}/src/DebugTransport.cpp
    ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}/src/DebugPublisher.cpp
    ${NOVA_CORE_TRANSPORT_DEBUG_ROOT}/src/DebugSubscriber.cpp
  )
  
  LIST( APPEND NOVA_CORE_TRANSPORT_DEBUG_SOURCES ${TRANSPORT_SOURCES} )
ENDIF()

IF( NOVA_CORE_TRANSPORT_DEBUG_SOURCES )
  LIST( REMOVE_DUPLICATES NOVA_CORE_TRANSPORT_DEBUG_SOURCES )
ENDIF()

IF( NOVA_CORE_TRANSPORT_DEBUG_INCLUDE_DIRS )
  LIST( REMOVE_DUPLICATES NOVA_CORE_TRANSPORT_DEBUG_INCLUDE_DIRS )
ENDIF()

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( NovaCore_Transport_Debug DEFAULT_MSG NOVA_CORE_TRANSPORT_DEBUG_SOURCES NOVA_CORE_TRANSPORT_DEBUG_INCLUDE_DIRS )
