IF( NOT NOVA_CORE_BASE_ROOT )
  IF( NOT NOVA_ROOT )
    SET( NOVA_CORE_BASE_ROOT /opt/nova/middleware )
  ELSE()
    SET( NOVA_CORE_BASE_ROOT ${NOVA_ROOT}/core-base )
  ENDIF()

  MESSAGE( STATUS "No NOVA_CORE_BASE_ROOT specified, using default: ${NOVA_CORE_BASE_ROOT}" )
ENDIF()

SET( NOVA_CORE_BASE_SOURCES
  ${NOVA_CORE_BASE_ROOT}/src/core-base.cpp
)

SET( NOVA_CORE_BASE_INCLUDE_DIRS
  ${NOVA_CORE_BASE_ROOT}/include
  ${NOVA_CORE_BASE_ROOT}/port/chibios/include
)

IF( NOVA_CORE_BASE_SOURCES )
  LIST( REMOVE_DUPLICATES NOVA_CORE_BASE_SOURCES )
ENDIF()

IF( NOVA_CORE_BASE_INCLUDE_DIRS )
  LIST( REMOVE_DUPLICATES NOVA_CORE_BASE_INCLUDE_DIRS )
ENDIF()

INCLUDE( FindPackageHandleStandardArgs )
FIND_PACKAGE_HANDLE_STANDARD_ARGS( NovaCore_Base DEFAULT_MSG NOVA_CORE_BASE_SOURCES NOVA_CORE_BASE_INCLUDE_DIRS )
